---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: ubuntu-10.04
  - name: debian-7.6
  - name: centos-6.5
  - name: centos-5.10
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[daemontools::default]
    attributes:
