---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: ubuntu-10.04
  - name: debian-7.6

suites:
  - name: default
    run_list:
      - recipe[test]
    attributes:

  - name: nostart-svscan
    run_list:
      - recipe[test::nostart-svscan]
    attributes:
      daemontools:
        start_svscan: false

  - name: source
    run_list:
      - recipe[daemontools::source]
    attributes:
      daemontools:
        start_svscan: false
        bin_dir: "/usr/local/bin"
